/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type FormationType = { 'two_candle' : null } |
  { 'multi_candle' : null } |
  { 'three_candle' : null } |
  { 'single' : null };
export interface Pattern {
  'id' : string,
  'formation' : string,
  'strategy' : string,
  'name' : string,
  'reliability' : Reliability,
  'formationType' : FormationType,
  'shortDescription' : string,
  'warnings' : string,
  'category' : PatternCategory,
  'psychology' : string,
}
export type PatternCategory = { 'indecision' : null } |
  { 'bearish_reversal' : null } |
  { 'bullish_reversal' : null } |
  { 'bearish_continuation' : null } |
  { 'bullish_continuation' : null };
export type Reliability = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface _SERVICE {
  'getAllPatterns' : ActorMethod<[], Array<Pattern>>,
  'getPatternById' : ActorMethod<[string], [] | [Pattern]>,
  'getPatternsByCategory' : ActorMethod<[PatternCategory], Array<Pattern>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];