/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Reliability = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const FormationType = IDL.Variant({
  'two_candle' : IDL.Null,
  'multi_candle' : IDL.Null,
  'three_candle' : IDL.Null,
  'single' : IDL.Null,
});
export const PatternCategory = IDL.Variant({
  'indecision' : IDL.Null,
  'bearish_reversal' : IDL.Null,
  'bullish_reversal' : IDL.Null,
  'bearish_continuation' : IDL.Null,
  'bullish_continuation' : IDL.Null,
});
export const Pattern = IDL.Record({
  'id' : IDL.Text,
  'formation' : IDL.Text,
  'strategy' : IDL.Text,
  'name' : IDL.Text,
  'reliability' : Reliability,
  'formationType' : FormationType,
  'shortDescription' : IDL.Text,
  'warnings' : IDL.Text,
  'category' : PatternCategory,
  'psychology' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllPatterns' : IDL.Func([], [IDL.Vec(Pattern)], ['query']),
  'getPatternById' : IDL.Func([IDL.Text], [IDL.Opt(Pattern)], ['query']),
  'getPatternsByCategory' : IDL.Func(
      [PatternCategory],
      [IDL.Vec(Pattern)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Reliability = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const FormationType = IDL.Variant({
    'two_candle' : IDL.Null,
    'multi_candle' : IDL.Null,
    'three_candle' : IDL.Null,
    'single' : IDL.Null,
  });
  const PatternCategory = IDL.Variant({
    'indecision' : IDL.Null,
    'bearish_reversal' : IDL.Null,
    'bullish_reversal' : IDL.Null,
    'bearish_continuation' : IDL.Null,
    'bullish_continuation' : IDL.Null,
  });
  const Pattern = IDL.Record({
    'id' : IDL.Text,
    'formation' : IDL.Text,
    'strategy' : IDL.Text,
    'name' : IDL.Text,
    'reliability' : Reliability,
    'formationType' : FormationType,
    'shortDescription' : IDL.Text,
    'warnings' : IDL.Text,
    'category' : PatternCategory,
    'psychology' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllPatterns' : IDL.Func([], [IDL.Vec(Pattern)], ['query']),
    'getPatternById' : IDL.Func([IDL.Text], [IDL.Opt(Pattern)], ['query']),
    'getPatternsByCategory' : IDL.Func(
        [PatternCategory],
        [IDL.Vec(Pattern)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };