/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Pattern {
    id: string;
    formation: string;
    strategy: string;
    name: string;
    reliability: Reliability;
    formationType: FormationType;
    shortDescription: string;
    warnings: string;
    category: PatternCategory;
    psychology: string;
}
export enum FormationType {
    two_candle = "two_candle",
    multi_candle = "multi_candle",
    three_candle = "three_candle",
    single = "single"
}
export enum PatternCategory {
    indecision = "indecision",
    bearish_reversal = "bearish_reversal",
    bullish_reversal = "bullish_reversal",
    bearish_continuation = "bearish_continuation",
    bullish_continuation = "bullish_continuation"
}
export enum Reliability {
    low = "low",
    high = "high",
    medium = "medium"
}
export interface backendInterface {
    getAllPatterns(): Promise<Array<Pattern>>;
    getPatternById(id: string): Promise<Pattern | null>;
    getPatternsByCategory(category: PatternCategory): Promise<Array<Pattern>>;
}
import type { FormationType as _FormationType, Pattern as _Pattern, PatternCategory as _PatternCategory, Reliability as _Reliability } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllPatterns(): Promise<Array<Pattern>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPatterns();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPatterns();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatternById(arg0: string): Promise<Pattern | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatternById(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatternById(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatternsByCategory(arg0: PatternCategory): Promise<Array<Pattern>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatternsByCategory(to_candid_PatternCategory_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatternsByCategory(to_candid_PatternCategory_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_FormationType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FormationType): FormationType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PatternCategory_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PatternCategory): PatternCategory {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Pattern_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Pattern): Pattern {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Reliability_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Reliability): Reliability {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Pattern]): Pattern | null {
    return value.length === 0 ? null : from_candid_Pattern_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    formation: string;
    strategy: string;
    name: string;
    reliability: _Reliability;
    formationType: _FormationType;
    shortDescription: string;
    warnings: string;
    category: _PatternCategory;
    psychology: string;
}): {
    id: string;
    formation: string;
    strategy: string;
    name: string;
    reliability: Reliability;
    formationType: FormationType;
    shortDescription: string;
    warnings: string;
    category: PatternCategory;
    psychology: string;
} {
    return {
        id: value.id,
        formation: value.formation,
        strategy: value.strategy,
        name: value.name,
        reliability: from_candid_Reliability_n4(_uploadFile, _downloadFile, value.reliability),
        formationType: from_candid_FormationType_n6(_uploadFile, _downloadFile, value.formationType),
        shortDescription: value.shortDescription,
        warnings: value.warnings,
        category: from_candid_PatternCategory_n8(_uploadFile, _downloadFile, value.category),
        psychology: value.psychology
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Reliability {
    return "low" in value ? Reliability.low : "high" in value ? Reliability.high : "medium" in value ? Reliability.medium : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    two_candle: null;
} | {
    multi_candle: null;
} | {
    three_candle: null;
} | {
    single: null;
}): FormationType {
    return "two_candle" in value ? FormationType.two_candle : "multi_candle" in value ? FormationType.multi_candle : "three_candle" in value ? FormationType.three_candle : "single" in value ? FormationType.single : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    indecision: null;
} | {
    bearish_reversal: null;
} | {
    bullish_reversal: null;
} | {
    bearish_continuation: null;
} | {
    bullish_continuation: null;
}): PatternCategory {
    return "indecision" in value ? PatternCategory.indecision : "bearish_reversal" in value ? PatternCategory.bearish_reversal : "bullish_reversal" in value ? PatternCategory.bullish_reversal : "bearish_continuation" in value ? PatternCategory.bearish_continuation : "bullish_continuation" in value ? PatternCategory.bullish_continuation : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Pattern>): Array<Pattern> {
    return value.map((x)=>from_candid_Pattern_n2(_uploadFile, _downloadFile, x));
}
function to_candid_PatternCategory_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PatternCategory): _PatternCategory {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PatternCategory): {
    indecision: null;
} | {
    bearish_reversal: null;
} | {
    bullish_reversal: null;
} | {
    bearish_continuation: null;
} | {
    bullish_continuation: null;
} {
    return value == PatternCategory.indecision ? {
        indecision: null
    } : value == PatternCategory.bearish_reversal ? {
        bearish_reversal: null
    } : value == PatternCategory.bullish_reversal ? {
        bullish_reversal: null
    } : value == PatternCategory.bearish_continuation ? {
        bearish_continuation: null
    } : value == PatternCategory.bullish_continuation ? {
        bullish_continuation: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
